[package]
name = "cas_ng_core"
version = "0.2.0"
edition = "2021"

[dependencies]
sha3 = "0.10"
blake3 = "1.4"
rand = "0.8"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
colored = "2.0" # FÃ¼r das bunte GUI im Terminal 
